---
- name: mutt
  apt:
      name: ["mutt", "msmtp", "gpgsm"]
      update_cache: yes
      state: present
  become: yes

- name: configuration directory
  file: 
    path: "/home/{{ user }}/.mutt"
    state: directory
    mode: 0755
    owner: "{{ user }}"

- name: mutt configuration
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
      - { src: '{{ playbook_dir }}/../../mutt/muttrc',
          dest: '/home/{{ user }}/.muttrc' }
      - { src: '{{ playbook_dir }}/../../mutt/account.google',
          dest: '/home/{{ user }}/.mutt/account.google' }
